# Generated by Django 3.1.6 on 2021-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
